swagger: '2.0'
info:
  title: title
  description: description
  version: 2.0.0

host: '--'
schemes:
  - https
basePath: /v2
produces:
  - application/json
paths:
  "/":
    get:
      description: description
      parameters:
      - name: cachebeater
        in: query
        description: Cachebeater string.
        required: false
        type: string
      responses:
        default:
          description: Invalid request.
          schema:
            "$ref": "#/definitions/Error"
definitions:
  Error:
    type: object
    description: A representation of a error
    properties:
      type:
        type: string
        description: The error type
      value:
        type: string
        description: Explanation of the error